source "https://rubygems.org"

gem "rails", "~> 7.2.3"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  gem "brakeman", require: false

  gem "rubocop-rails-omakase", require: false
end

gem "dotenv-rails", groups: [:development, :test]

gem "onlinepayments-sdk-ruby", "~> 6.4.0"

gem "dry-types", "~> 1.9"

gem "dry-validation", "~> 1.10"

gem "rack-cors", require: "rack/cors"
