# Application configuration
spring.application.name=OnlinePayments-SDK-Java-Examples-Application
server.port=3000
# Direct SDK Configuration
merchantId=<your-merchant-id>
apiKey=<your-merchant-key>
apiSecret=<your-merchant-secret>
apiEndpoint=<your-api-endpoint>